import uuid
from sqlalchemy import Column, Integer, ForeignKey, Text, String, func, DateTime
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.core.database import Base


class JobSummary(Base):
    __tablename__ = "job_summaries"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_id = Column(UUID(as_uuid=True), ForeignKey("jobs.id", ondelete="CASCADE"), unique=True, nullable=False, index=True)
    
    # Financial Analytics (stored as JSON/JSONB objects)
    total_spend = Column(JSONB, nullable=False)  # {"USD": 12000, "INR": 98000}
    top_merchants = Column(JSONB, nullable=False)  # [{"merchant": "Amazon", "amount": 8000.0, "count": 4}]
    anomaly_count = Column(Integer, nullable=False, default=0)
    
    # Executive Narrative generated by LLM
    financial_narrative = Column(Text, nullable=True)
    risk_level = Column(String, nullable=False, default="LOW")  # LOW, MEDIUM, HIGH
    
    # Token usage tracker
    token_usage = Column(JSONB, nullable=True)  # {"prompt_tokens": 520, "completion_tokens": 150}

    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    job = relationship("Job", back_populates="summary")
